title: in erTRACE
description: Helppage for erTrace
theme: just-the-docs

url: https://github.com/erminas/erTrace-helppage
logo: /assets/erTRACELOGOv1.svg

favicon_ico: /assets/erTraceIcon.svg

color_scheme: erTrace.scss

aux_links:
  erminas: https://erminas.de/
plugins:
  - jekyll-default-layout

exclude:
  - pipeline/
