title: YOUR TITLE
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://YOUR-USERNAME.github.io/YOUR-SITE-NAME

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
plugins:
  - jekyll-default-layout
