trigger:
  - main
  - release/*

pr:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build App
    jobs:
      - job: Documentation
        displayName: Documentation
        variables:
          - group: ertrace-docs
        steps:
          - template: template/dependencies.yml
          - template: template/build.yml
          - template: template/deploy.yml
            parameters:
              deploymentSlot: development
